apiVersion: v1
kind: Service
metadata:
  name: customerorderweb-service
spec:
  selector: 
    app: clear
    release: "1"
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30081
  type: NodePort

